apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: nodejs
spec:
  containers:
  - name: app
    image: zapolskas/oxylabs-app
    ports:
    - containerPort: 3000
    # data volume from where app read data written by redis
    volumeMounts:
    - name: data
      mountPath: /data
      readOnly: false
    env:
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: redis-secret
            key: redisPassword
      - name: REDIS_HOST
        value: $(REDIS_SERVICE_HOST)
      #- name: REDIS_PASSWORD
      #  value: "verysecurepassword"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: redis-data