apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - name: redis
    port: {{ .Values.redisPort }}
    targetPort: {{ .Values.redisPort }}
  selector:
    app: redis